# Generated by Django 3.2.7 on 2021-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
